# ============================== Version ================================ #
# ======================================================================= #

version: 0.0.0+0

# ============================= Information ============================= #
# ======================================================================= #

name: widget
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

# ============================ Dependencies ============================= #
# ======================================================================= #

dependencies:
  flutter:
    sdk: flutter

  library:
    path: ../library

# ================================ Assets =============================== #
# ======================================================================= #

flutter:
  uses-material-design: true